- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-n01517377
    - profile-n01517377
    - user-n01517377
    - webserver-n01517377

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"

